config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "hobbies#index"
  resources :users, only: :show
  resources :hobbies do
    resources :comments, only: :create
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: 'アート' },
    { id: 3, name: '育成／飼育' },
    { id: 4, name: 'イベント' },
    { id: 5, name: '演奏' },
    { id: 6, name: '学習' },
    { id: 7, name: '観察' },
    { id: 8, name: '鑑賞' },
    { id: 9, name: '観戦' },
    { id: 10, name: 'グルメ' },
    { id: 11, name: 'ゲーム' },
    { id: 12, name: '健康／美容' },
    { id: 13, name: '収集／採取' },
    { id: 14, name: 'スポーツ' },
    { id: 15, name: '体験' },
    { id: 16, name: '特技' },
    { id: 17, name: 'ミュージック' },
    { id: 18, name: 'ものづくり' },
    { id: 19, name: '料理' },
    { id: 20, name: '旅行' },
    { id: 21, name: 'その他' }
  ]

  include ActiveHash::Associations
  has_many :hobbies
end

app/models/comment.rb
class Comment < ApplicationRecord

  validates :comment, presence: true

  belongs_to :hobby
  belongs_to :user
end

app/models/count.rb
class Count < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '/回' },
    { id: 3, name: '/日' },
    { id: 4, name: '/週' },
    { id: 5, name: '/月' },
    { id: 6, name: '/半年'},
    { id: 7, name: '/年' }
  ]

  include ActiveHash::Associations
  has_many :hobbies
end

app/models/from.rb
class From < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '北海道' },
    { id: 3, name: '青森県' },
    { id: 4, name: '岩手県' },
    { id: 5, name: '宮城県' },
    { id: 6, name: '秋田県' },
    { id: 7, name: '山形県' },
    { id: 8, name: '福島県' },
    { id: 9, name: '茨城県' },
    { id: 10, name: '栃木県' },
    { id: 11, name: '群馬県' },
    { id: 12, name: '埼玉県' },
    { id: 13, name: '千葉県' },
    { id: 14, name: '東京都' },
    { id: 15, name: '神奈川県' },
    { id: 16, name: '新潟県' },
    { id: 17, name: '富山県' },
    { id: 18, name: '石川県' },
    { id: 19, name: '福井県' },
    { id: 20, name: '山梨県' },
    { id: 21, name: '長野県' },
    { id: 22, name: '岐阜県' },
    { id: 23, name: '静岡県' },
    { id: 24, name: '愛知県' },
    { id: 25, name: '三重県' },
    { id: 26, name: '滋賀県' },
    { id: 27, name: '京都府' },
    { id: 28, name: '大阪府' },
    { id: 29, name: '兵庫県' },
    { id: 30, name: '奈良県' },
    { id: 31, name: '和歌山県' },
    { id: 32, name: '鳥取県' },
    { id: 33, name: '島根県' },
    { id: 34, name: '岡山県' },
    { id: 35, name: '広島県' },
    { id: 36, name: '山口県' },
    { id: 37, name: '徳島県' },
    { id: 38, name: '香川県' },
    { id: 39, name: '愛媛県' },
    { id: 40, name: '高知県' },
    { id: 41, name: '福岡県' },
    { id: 42, name: '佐賀県' },
    { id: 43, name: '長崎県' },
    { id: 44, name: '熊本県' },
    { id: 45, name: '大分県' },
    { id: 46, name: '宮崎県' },
    { id: 47, name: '鹿児島県' },
    { id: 48, name: '沖縄県' }
  ]

  include ActiveHash::Associations
  has_many :users
end

app/models/hobby.rb
class Hobby < ApplicationRecord
  self.inheritance_column = :_type_disabled 

  with_options presence: true do
    validates :image
    validates :type
    validates :text
    validates :user_id
  end

  belongs_to :user
  has_many :comments, dependent: :destroy
  has_one_attached :image

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :where
  belongs_to :category
  belongs_to :count
  belongs_to :from

  validates :where_id, numericality: { other_than: 1 , message: "can't be blank"}
  validates :category_id, numericality: { other_than: 1 , message: "can't be blank"}
end

app/models/user.rb
class User < ApplicationRecord
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  with_options presence: true do
    validates :nickname
    validates :last_name
    validates :first_name
    validates :last_name_kana
    validates :first_name_kana
    validates :city
    validates :number
    validates :phone, format: { with: /\A\d{10,11}\z/, message: "is 10 or 11 digits only" }
    validates :birthday
    validates :skill
    validates :profile
  end
       
  has_many :hobbies
  has_many :comments
       
  PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?[\d])[a-z\d]+\z/i.freeze
  validates_format_of :password, with: PASSWORD_REGEX, message: 'には英字と数字の両方を含めて設定してください'
       
  with_options presence: true, format: { with: /\A[ぁ-んー]+\z/, message: 'ひらがなを使用してください' } do
    validates :last_name_kana
    validates :first_name_kana
  end
       
  with_options presence: true, format: { with: /\A[ぁ-んァ-ヶ一-龥々ー]+\z/, message: '全角（漢字・ひらがな・カタカナ）を使用してください' } do
    validates :last_name
    validates :first_name
  end

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :from

  validates :from_id, numericality: { other_than: 1 , message: "can't be blank"} 
end

app/models/where.rb
class Where < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: 'indoor' },
    { id: 3, name: 'outdoor' }
  ]

  include ActiveHash::Associations
  has_many :hobbies
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :last_name, :first_name, :last_name_kana, :first_name_kana, :from_id, :city, :number, :phone, :birthday, :skill, :profile])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  def create
    @comment = Comment.new(comment_params)
    if @comment.save
      redirect_to hobby_path(@comment.hobby)
    else
      @hobby = @comment.hobby
      @comments = @hobby.comments
      render "hobby/show"
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:comment).merge(user_id: current_user.id, hobby_id: params[:hobby_id])
  end

end

app/controllers/hobbies_controller.rb
class HobbiesController < ApplicationController
  before_action :move_to_index, except: [ :index, :show]

  def index
    @hobbies = Hobby.order(created_at: :desc).first(3)
    @hobbies2 = Hobby.order(created_at: :desc)
  end

  def new
    @hobby = Hobby.new
  end

  def create
    @hobby = Hobby.new(hobby_params)
    if @hobby.save
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @hobby = Hobby.find(params[:id])
    @comment = Comment.new
    @comments = @hobby.comments.includes(:user)
  end

  def edit
    @hobby = Hobby.find(params[:id])
    unless @hobby.user_id == current_user.id
      redirect_to action: :index
    end
  end

  def update
    @hobby = Hobby.find(params[:id])
    if @hobby.update(hobby_params)
      redirect_to hobby_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    hobby = Hobby.find(params[:id])
    hobby.destroy
    redirect_to root_path
  end

  private
  def move_to_index
    unless user_signed_in?
      redirect_to action: :index
    end
  end

  def hobby_params
    params.require(:hobby).permit(:image, :where_id, :category_id, :type, :text, :cost, :count_id, :from_id, :city).merge(user_id: current_user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/hobbies_helper.rb
module HobbiesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/hobbies/_form.html.erb
<%= form_with model: @hobby, local: true do |f|%>

<%= render 'shared/error_messages', model: f.object %>

  <%# 投稿画像 %>
  <div class="img-upload">
    <div class="form-text">
      投稿画像
      <span class="indispensable">必須</span>
    </div>
    <div class="click-upload">
      <p>
        クリックしてファイルをアップロード
      </p>
      <%= f.file_field :image, id:"item-image" %>
    </div>
  </div>
  <%# /投稿画像 %>

  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">趣味の場所</label>
      <span class="indispensable">必須</span>
    </div>
    <%= f.collection_select(:where_id, Where.all, :id, :name, {}, {class:"select-box", id:"prefecture"}) %>
  </div>

  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">区分</label>
      <span class="indispensable">必須</span>
    </div>
    <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"select-box", id:"prefecture"}) %>
  </div>  

  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">趣味の種類</label>
      <span class="indispensable">必須</span>
    </div>
    <%= f.text_field :type, class:"input-default", id:"type", placeholder:"例）スカイダイビング"%>
  </div>

  <div class="form-group">

    <div class='form-text-wrap'>
      <label class="form-text">投稿内容の紹介</label>
      <span class="indispensable">必須</span>
    </div>
    <%= f.text_area :text, class:"input-default", id:"text", placeholder:"例）一年前からやってみたいと思っていたスカイダイビングを始めました。"%>
  </div>

  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">費用/月謝</label>
    </div>
    <div class='input-cost-wrap'>
      <%= f.text_field :cost, class:"input-default", id:"cost", placeholder:"例）5000"%><p>円</p>
      <%= f.collection_select(:count_id, Count.all, :id, :name, {}, {class:"select-box", id:"prefecture"}) %>
    </div>
  </div>

  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">趣味を行った場所</label>
    </div>
    <div class='input-cost-wrap'>
      <label class="form-text">都道府県
        <%= f.collection_select(:from_id, From.all, :id, :name, {}, {class:"select-box", id:"prefecture"}) %>
      </label>
      <label class="form-text">市区町村
        <%= f.text_field :city, class:"input-default", id:"cost", placeholder:"例）浜松市"%>
      </label>
    </div>
  </div>

  <div class="actions">
    <%= f.submit "保存する", class: :form__btn  %>
  </div>
<% end %>

app/views/hobbies/_hobby.html.erb
<div class="index_item">
  <div class="index_type_idd">
    <%= hobby.type %>
  </div>
  <%= link_to image_tag(hobby.image, class: :index_image_idd ), hobby_path(hobby.id) %>
    <p class="index_category">
      <%= link_to hobby.category.name, root_path %>
    </p>
    <%= link_to "投稿：" + hobby.user.nickname + "さん", user_path(hobby.user_id), class: :index_user_idd %>
</div>

app/views/hobbies/edit.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">投稿内容編集</h2>
      <%= render partial: 'form' %>
    </div>
  </div>
</div>

app/views/hobbies/index.html.erb
<main class="main">
  <div class="inner">
    <% if user_signed_in? %>
      <div class="greeting">
        <%= "Hello," %>
        <%= link_to current_user.nickname + "さん", user_path(current_user.id), class: :greeting__link%>
      </div>
    <% end %>

    <div class="index_title">
    <%= "NEW"  %>
    </div>
    <div class="index_new">
      <%= render partial: 'hobby', collection: @hobbies %>
    </div>

    <div class="category_title">
    <%= "Category"  %>
    </div>

    <div class="index_category_item">
      <div class="index_category_btn">
      <%= link_to "アート", root_path, class: :index_category_btn_idd %>
        <% @hobbies2.each do |hobby| %>
          <% if hobby.category_id == 2 %>
            <div class="category_image">
              <%= link_to image_tag(hobby.image, class: :index_image_idd ), hobby_path(hobby.id) %>
            </div>
            <% break %>
          <% end %>   
        <% end %>
      </div>

      <div class="index_category_btn">
      <%= link_to "育成／飼育", root_path, class: :index_category_btn_idd %>
        <% @hobbies2.each do |hobby| %>
          <% if hobby.category_id == 3 %>
            <div class="category_image">
              <%= link_to image_tag(hobby.image, class: :index_image_idd ), hobby_path(hobby.id) %>
            </div>
            <% break %>
          <% end %>
        <% end %>
      </div>

      <div class="index_category_btn">
      <%= link_to "イベント", root_path, class: :index_category_btn_idd %>
        <% @hobbies2.each do |hobby| %>
          <% if hobby.category_id == 4 %>
            <div class="category_image">
              <%= link_to image_tag(hobby.image, class: :index_image_idd ), hobby_path(hobby.id) %>
            </div>
            <% break %>
          <% end %>
      <% end %>
      </div>

      <div class="index_category_btn">
      <%= link_to "演奏", root_path, class: :index_category_btn_idd %>
        <% @hobbies2.each do |hobby| %>
          <% if hobby.category_id == 5 %>
            <div class="category_image">
              <%= link_to image_tag(hobby.image, class: :index_image_idd ), hobby_path(hobby.id) %>
            </div>
            <% break %>
          <% end %>
      <% end %>
      </div>

      <div class="index_category_btn">
      <%= link_to "学習", root_path, class: :index_category_btn_idd %>
        <% @hobbies2.each do |hobby| %>
          <% if hobby.category_id == 6 %>
            <div class="category_image">
              <%= link_to image_tag(hobby.image, class: :index_image_idd ), hobby_path(hobby.id) %>
            </div>
            <% break %>
          <% end %>
      <% end %>
      </div>

      <div class="index_category_btn">
      <%= link_to "観察", root_path, class: :index_category_btn_idd %>
        <% @hobbies2.each do |hobby| %>
          <% if hobby.category_id == 7 %>
            <div class="category_image">
              <%= link_to image_tag(hobby.image, class: :index_image_idd ), hobby_path(hobby.id) %>
            </div>
            <% break %>
          <% end %>
      <% end %>
      </div>      

      <div class="index_category_btn">
      <%= link_to "鑑賞", root_path, class: :index_category_btn_idd %>
        <% @hobbies2.each do |hobby| %>
          <% if hobby.category_id == 8 %>
            <div class="category_image">
              <%= link_to image_tag(hobby.image, class: :index_image_idd ), hobby_path(hobby.id) %>
            </div>
            <% break %>
          <% end %>
      <% end %>
      </div>

      <div class="index_category_btn">
      <%= link_to "観戦", root_path, class: :index_category_btn_idd %>
        <% @hobbies2.each do |hobby| %>
          <% if hobby.category_id == 9 %>
            <div class="category_image">
              <%= link_to image_tag(hobby.image, class: :index_image_idd ), hobby_path(hobby.id) %>
            </div>
            <% break %>
          <% end %>
      <% end %>
      </div>

      <div class="index_category_btn">
      <%= link_to "グルメ", root_path, class: :index_category_btn_idd %>
        <% @hobbies2.each do |hobby| %>
          <% if hobby.category_id == 10 %>
            <div class="category_image">
              <%= link_to image_tag(hobby.image, class: :index_image_idd ), hobby_path(hobby.id) %>
            </div>
            <% break %>
          <% end %>
      <% end %>
      </div>

      <div class="index_category_btn">
      <%= link_to "ゲーム", root_path, class: :index_category_btn_idd %>
        <% @hobbies2.each do |hobby| %>
          <% if hobby.category_id == 11 %>
            <div class="category_image">
              <%= link_to image_tag(hobby.image, class: :index_image_idd ), hobby_path(hobby.id) %>
            </div>
            <% break %>
          <% end %>
      <% end %>
      </div>
    </div>

    <div class="index_category_item">
      <div class="index_category_btn">
      <%= link_to "健康／美容", root_path, class: :index_category_btn_idd %>
        <% @hobbies2.each do |hobby| %>
          <% if hobby.category_id == 12 %>
            <div class="category_image">
              <%= link_to image_tag(hobby.image, class: :index_image_idd ), hobby_path(hobby.id) %>
            </div>
            <% break %>
          <% end %>
      <% end %>
      </div>

      <div class="index_category_btn">
      <%= link_to "収集／採取", root_path, class: :index_category_btn_idd %>
        <% @hobbies2.each do |hobby| %>
          <% if hobby.category_id == 13 %>
            <div class="category_image">
              <%= link_to image_tag(hobby.image, class: :index_image_idd ), hobby_path(hobby.id) %>
            </div>
            <% break %>
          <% end %>
      <% end %>
      </div>

      <div class="index_category_btn">
      <%= link_to "スポーツ", root_path, class: :index_category_btn_idd %>
        <% @hobbies2.each do |hobby| %>
          <% if hobby.category_id == 14 %>
            <div class="category_image">
              <%= link_to image_tag(hobby.image, class: :index_image_idd ), hobby_path(hobby.id) %>
            </div>
            <% break %>
          <% end %>
      <% end %>
      </div>

      <div class="index_category_btn">
      <%= link_to "体験", root_path, class: :index_category_btn_idd %>
        <% @hobbies2.each do |hobby| %>
          <% if hobby.category_id == 15 %>
            <div class="category_image">
              <%= link_to image_tag(hobby.image, class: :index_image_idd ), hobby_path(hobby.id) %>
            </div>
            <% break %>
          <% end %>
      <% end %>
      </div>

      <div class="index_category_btn">
      <%= link_to "特技", root_path, class: :index_category_btn_idd %>
        <% @hobbies2.each do |hobby| %>
          <% if hobby.category_id == 16 %>
            <div class="category_image">
              <%= link_to image_tag(hobby.image, class: :index_image_idd ), hobby_path(hobby.id) %>
            </div>
            <% break %>
          <% end %>
      <% end %>
      </div>

      <div class="index_category_btn">
      <%= link_to "ミュージック", root_path, class: :index_category_btn_idd %>
        <% @hobbies2.each do |hobby| %>
          <% if hobby.category_id == 17 %>
            <div class="category_image">
              <%= link_to image_tag(hobby.image, class: :index_image_idd ), hobby_path(hobby.id) %>
            </div>
            <% break %>
          <% end %>
      <% end %>
      </div>

      <div class="index_category_btn">
      <%= link_to "ものづくり", root_path, class: :index_category_btn_idd %>
        <% @hobbies2.each do |hobby| %>
          <% if hobby.category_id == 18 %>
            <div class="category_image">
              <%= link_to image_tag(hobby.image, class: :index_image_idd ), hobby_path(hobby.id) %>
            </div>
            <% break %>
          <% end %>
      <% end %>
      </div>

      <div class="index_category_btn">
      <%= link_to "料理", root_path, class: :index_category_btn_idd %>
        <% @hobbies2.each do |hobby| %>
          <% if hobby.category_id == 19 %>
            <div class="category_image">
              <%= link_to image_tag(hobby.image, class: :index_image_idd ), hobby_path(hobby.id) %>
            </div>
            <% break %>
          <% end %>
      <% end %>
      </div>

      <div class="index_category_btn">
      <%= link_to "旅行", root_path, class: :index_category_btn_idd %>
        <% @hobbies2.each do |hobby| %>
          <% if hobby.category_id == 20 %>
            <div class="category_image">
              <%= link_to image_tag(hobby.image, class: :index_image_idd ), hobby_path(hobby.id) %>
            </div>
            <% break %>
          <% end %>
      <% end %>
      </div>

      <div class="index_category_btn">
      <%= link_to "その他", root_path, class: :index_category_btn_idd %>
        <% @hobbies2.each do |hobby| %>
          <% if hobby.category_id == 21 %>
            <div class="category_image">
              <%= link_to image_tag(hobby.image, class: :index_image_idd ), hobby_path(hobby.id) %>
            </div>
            <% break %>
          <% end %>
      <% end %>
      </div>
    </div>
   </div>
</main>

app/views/hobbies/new.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">新規投稿内容</h2>
        <%= render partial: 'form' %>
    </div>
  </div>
</div>

app/views/hobbies/show.html.erb
<main class="main">
  <div class="inner">
    <div class="hobby__wrapper">
      <p class="hobby__hedding">
        <%= @hobby.type %>
      </p>
      <%= link_to "投稿者:" + @hobby.user.nickname + "さん", user_path(@hobby.user_id), class: :hobby__user %>
      <% if user_signed_in? && @hobby.user_id == current_user.id %>
        <div class="hobby__manage">
          <%= link_to "編集する", edit_hobby_path, class: :hobby__btn %>
          <%= link_to "削除する", hobby_path(@hobby.id), data: { turbo_method: :delete }, class: :hobby__btn %>
        </div>
      <% end %>
      <div class="hobby__image">
        <%= image_tag(@hobby.image) %>
      </div>
      <div class="hobby__body">
        <div class="hobby__detail">
          <p><span class="detail__title">Where</span></p>
          <p class="detail__message">
            <%= @hobby.where.name %>
          </p>
        </div>
        <div class="hobby__detail">
          <p><span class="detail__title">Category</span></p>
          <p class="detail__message">
            <%= @hobby.category.name %>
          </p>
        </div>
        <div class="hobby__detail">
          <p><span class="detail__title">Cost</span></p>
          <p class="detail__message">
            <%= @hobby.cost.to_s + "円" + @hobby.count.name %>
          </p>
        </div>
        <div class="hobby__detail">
          <p><span class="detail__title">Address</span></p>
          <p class="detail__message">
            <%= @hobby.from.name + @hobby.city %>
          </p>
        </div>
        <div class="hobby__detail">
          <p><span class="detail__title">Text</span></p>
          <p class="detail__message">
            <%= @hobby.text %>
          </p>
        </div>
      </div>
      <div class="hobby__comments">
        <% if user_signed_in? %>
          <%= form_with model: [@hobby, @comment],local: true do |f|%>
            <div class="field">
              <%= f.label :comment, "comment" %><br />
              <%= f.text_field :comment, id:"comment_content" %>
            </div>
            <div class="actions">
              <%= f.submit "送信する", class: :form__btn  %>
            </div>
          <% end %>
        <% end %>
        <ul class="comments_lists">
          <% @comments.each do |comment| %>
            <li class="comments_list">
              <%= comment.comment %>
              <%= link_to comment.user.nickname, user_path(comment.user_id), class: :comment_user %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Find a hobby!</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP:400,700,900&display=swap" rel="stylesheet">
  </head>

  <body>
    <header class="header">
      <div class="inner">
        <div class="nav">
          <div class="nav__left">
            <%= link_to image_tag("logo.png", class: :logo), root_path %>
          </div>
          <% if user_signed_in? %>
            <div class="nav__right">
              <%= link_to "ログアウト", destroy_user_session_path, data: { turbo_method: :delete }, class: :nav__logout %>
              <%= link_to "New Posts", new_hobby_path, class: :nav__btn %>
            </div>
          <% else %>
            <div class="nav__right">
              <%= link_to "ログイン", new_user_session_path, class: :nav__btn %>
              <%= link_to "新規登録", new_user_registration_path, class: :nav__btn %>
            </div>
          <% end %>
        </div>
      </div>
    </header>
    <%= yield %>
    <footer class="footer">
      <p class="copyright">Copyright © FIND A HOBBY! rights reserved.</p>
    </footer>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/users/show.html.erb
<div class="main">
  <div class="inner">
    <div class="user__wrapper">
      <h2 class="page-heading">
        <%= @user.nickname + "さんのプロフィール" %>
      </h2>
      <table class="table">
        <tbody>
          <tr>
            <th class="table__col1">ニックネーム</th>
            <td class="table__col2"><%= @user.nickname %></td>
          </tr>
          <tr>
            <th class="table__col1">居住地</th>
            <td class="table__col2"><%= @user.from.name %></td>
          </tr>
          <tr>
            <th class="table__col1">お誕生日</th>
            <td class="table__col2"><%= @user.birthday.strftime("%Y年%m月%d日") %></td>
          </tr>
          <tr>
            <th class="table__col1">特技</th>
            <td class="table__col2"><%= @user.skill %></td>
          </tr>
          <tr>
            <th class="table__col1">自己紹介</th>
            <td class="table__col2"><%= @user.profile %></td>
          </tr>
        </tbody>
      </table>
      <h2 class="page-heading">
        <%= @user.nickname + "さんの投稿" %>
      </h2>
      <div class="user__card">
        <%= render partial: 'hobbies/hobby', collection: @user.hobbies %>
      </div>
    </div>
  </div>
</div>